# Generated by Django 2.2.10 on 2020-02-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('path', models.FilePathField(verbose_name='本机地址')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
