# Generated by Django 2.2.10 on 2020-02-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20200205_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='secret',
            field=models.BooleanField(default=False, verbose_name='是否加密'),
        ),
    ]
